add VPS_PORT

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -11,7 +11,6 @@ on:
       - .github/workflows/*-backend.yml
 
 jobs:
-
   compile:
     runs-on: self-hosted
     name: Compile project
@@ -64,7 +63,6 @@ jobs:
           echo "Running unit tests..."
           ./mvnw clean test
 
-
   build:
     runs-on: self-hosted
     name: Build backend
@@ -113,7 +111,7 @@ jobs:
           cd book-network
           chmod +x mvnw
 
-      - name: Build project
+      - name: Build project for Docker image
         run: |
           cd book-network
           echo "Building project for Docker image..."
@@ -124,7 +122,8 @@ jobs:
         run: |
           cd book-network
           echo "Extracting project version..."
-          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
+          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
@@ -139,10 +138,10 @@ jobs:
           file: docker/backend/Dockerfile
           push: true
           platforms: linux/amd64
-          tags: ${{secrets.DOCKERHUB_USERNAME}}/bsn-api:${{ steps.extract_version.outputs.VERSION }},${{secrets.DOCKERHUB_USERNAME}}/bsn-api:latest
+          tags: ${{secrets.DOCKERHUB_USERNAME}}/bsn-api:${{ env.VERSION }},${{secrets.DOCKERHUB_USERNAME}}/bsn-api:latest
           build-args: |
             PROFILE=dev
-            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
+            APP_VERSION=${{ env.VERSION }}
 
   deploy:
     name: Deploy backend
@@ -153,12 +152,12 @@ jobs:
         run: |
           echo "Creating deployment folder on server..."
           echo "sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} mkdir -p ci-cd"
-          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd" || (echo "Error during SSH command" exit 1)
+          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd" || (echo "Error during SSH command" && exit 1)
 
       - name: Copy docker-compose file
         run: |
           echo "Copying docker-compose file to server..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }}  scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml || (echo "Error during SSH command" exit 1)
+          sshpass -p ${{ secrets.VPS_PASSWORD }} scp -P ${{ secrets.VPS_PORT }} docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml || (echo "Error during SCP command" && exit 1)
 
       - name: Set ENV variables and deploy
         run: |
@@ -171,4 +170,3 @@ jobs:
           docker-compose -f docker-compose.yml pull -q
           docker-compose -f docker-compose.yml up -d
           EOF
-#
