add VPS_PORT

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -11,7 +11,6 @@ on:
       - .github/workflows/*-backend.yml
 
 jobs:
-
   compile:
     runs-on: self-hosted
     name: Compile project
@@ -26,11 +25,6 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-
-      - name: Make mvnw executable
-        run: |
-          cd book-network
-          chmod +x mvnw
 
       - name: Compile project
         run: |
@@ -53,22 +47,16 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Make mvnw executable
-        run: |
-          cd book-network
-          chmod +x mvnw
-
       - name: Running unit Tests
         run: |
           cd book-network
           echo "Running unit tests..."
           ./mvnw clean test
 
-
   build:
     runs-on: self-hosted
     name: Build backend
-    needs: [ compile, unit-tests ]
+    needs: [compile, unit-tests]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -80,11 +68,6 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-
-      - name: Make mvnw executable
-        run: |
-          cd book-network
-          chmod +x mvnw
 
       - name: Build project
         run: |
@@ -95,7 +78,7 @@ jobs:
   build-image:
     name: Build Docker image
     runs-on: self-hosted
-    needs: [ build ]
+    needs: [build]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -107,11 +90,6 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-
-      - name: Make mvnw executable
-        run: |
-          cd book-network
-          chmod +x mvnw
 
       - name: Build project
         run: |
@@ -152,22 +130,21 @@ jobs:
       - name: Create deployment folder
         run: |
           echo "Creating deployment folder on server..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd"
+          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -p "${{ secrets.VPS_PORT }}" "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}" "mkdir -p ci-cd" || (echo "Error during SSH command"; exit 1)
 
       - name: Copy docker-compose file
         run: |
           echo "Copying docker-compose file to server..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }}  scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml
+          sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -P "${{ secrets.VPS_PORT }}" docker-compose.yml "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}":ci-cd/docker-compose.yml || (echo "Error during SCP command"; exit 1)
 
       - name: Set ENV variables and deploy
         run: |
           echo "Setting environment variables and deploying..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
-          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
-          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
-          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
+          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -p "${{ secrets.VPS_PORT }}" "${{ secrets.VPS_USERNAME }}"@"${{ secrets.VPS_IP }}" <<EOF
+          export EMAIL_HOST_NAME="${{ secrets.EMAIL_HOST_NAME }}"
+          export EMAIL_USER_NAME="${{ secrets.EMAIL_USER_NAME }}"
+          export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
           cd ci-cd
           docker-compose -f docker-compose.yml pull -q
           docker-compose -f docker-compose.yml up -d
           EOF
-#
