исправил workflow, чтобы первым шагом поднималась БД

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -11,6 +11,47 @@ on:
       - .github/workflows/*-backend.yml
 
 jobs:
+  deployBD:
+    name: Deploy BD
+    runs-on: self-hosted
+    needs: [ build-image ]
+    steps:
+      - name: Setup SSH key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Add server to known hosts
+        run: |
+          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
+
+      - name: Create deployment folder
+        run: |
+          echo "Creating deployment folder on server..."
+          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd-bd" || (echo "Error during SSH command" && exit 1)
+
+      - name: Check current directory content
+        run: |
+          echo "Checking current directory content..."
+          ls -la
+
+      - name: Copy docker-compose file
+        run: |
+          echo "Copying docker-compose file to server..."
+          scp -P ${{ secrets.VPS_PORT }}  docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd-bd/docker-compose.yml || (echo "Error during SCP command" && exit 1)
+
+      - name: Set ENV variables and deploy
+        run: |
+          echo "Setting environment variables and deploying..."
+          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
+          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
+          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
+          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
+          cd ci-cd
+          docker-compose -f docker-compose.yml pull -q
+          docker-compose -f docker-compose.yml up -d
+          EOF
+
   compile:
     runs-on: self-hosted
     name: Compile project
