add VPS_PORT

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -170,7 +170,7 @@ jobs:
       - name: Copy docker-compose file
         run: |
           echo "Copying docker-compose file to server..."
-          scp -P ${{ secrets.VPS_PORT }} docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml || (echo "Error during SCP command" && exit 1)
+          scp -P ${{ secrets.VPS_PORT }}  book-network/docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml || (echo "Error during SCP command" && exit 1)
 
       - name: Set ENV variables and deploy
         run: |
diff --git a/.github/workflows/pipeline-frontend.yml b/.github/workflows/pipeline-frontend.yml
--- a/.github/workflows/pipeline-frontend.yml
+++ b/.github/workflows/pipeline-frontend.yml
@@ -5,8 +5,8 @@ on:
     branches:
       - main
     paths:
-      - book-network/**
-      - docker/backend/**
+      - book-network-ui/**
+      - docker/frontend/**
       - 'docker-compose.yml'
       - .github/workflows/*-frontend.yml
 
@@ -29,8 +29,9 @@ jobs:
       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
-          username: ${{secrets.DOCKERHUB_USERNAME}}
-          password: ${{secrets.DOCKERHUB_TOKEN}}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
       - name: Build & Push to DockerHub
         uses: docker/build-push-action@v5
         with:
@@ -38,7 +39,7 @@ jobs:
           file: docker/frontend/Dockerfile
           push: true
           platforms: linux/amd64
-          tags: ${{secrets.DOCKERHUB_USERNAME}}/bsn-ui:${{ steps.extract_version.outputs.VERSION }},${{secrets.DOCKERHUB_USERNAME}}/bsn-ui:latest
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:latest
           build-args: |
             APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
             # Add more build arguments if needed
@@ -48,20 +49,29 @@ jobs:
     runs-on: self-hosted
     needs: [ build-image ]
     steps:
+      - name: Setup SSH key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Add server to known hosts
+        run: |
+          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
+
       - name: Create deployment folder
         run: |
           echo "Creating deployment folder on server..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd"
+          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ci-cd-ui" || (echo "Error during SSH command" && exit 1)
 
       - name: Copy docker-compose file
         run: |
           echo "Copying docker-compose file to server..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }} scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml
+          scp -P ${{ secrets.VPS_PORT }} book-network-ui/docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd-ui/docker-compose.yml || (echo "Error during SCP command" && exit 1)
 
       - name: Set ENV variables and deploy
         run: |
           echo "Setting environment variables and deploying..."
-          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
+          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
           cd ci-cd
           docker-compose -f docker-compose.yml pull -q
           docker-compose -f docker-compose.yml up -d
